export const data = [
  { id: 1, name: { firstName: 'Juan', lastName: 'Hernández' }, address: 'Calle Reforma 123', city: 'Ciudad de México', state: 'CDMX' },
  { id: 2, name: { firstName: 'María', lastName: 'García' }, address: 'Avenida Juárez 456', city: 'Guadalajara', state: 'Jalisco' },
  { id: 3, name: { firstName: 'Luis', lastName: 'Martínez' }, address: 'Calle Hidalgo 789', city: 'Monterrey', state: 'Nuevo León' },
  { id: 4, name: { firstName: 'Ana', lastName: 'López' }, address: 'Avenida Madero 101', city: 'Puebla', state: 'Puebla' },
  { id: 5, name: { firstName: 'Carlos', lastName: 'Pérez' }, address: 'Boulevard Díaz Ordaz 202', city: 'Tijuana', state: 'Baja California' },
  { id: 6, name: { firstName: 'Sofía', lastName: 'Ramírez' }, address: 'Calle Morelos 303', city: 'Mérida', state: 'Yucatán' },
  { id: 7, name: { firstName: 'Javier', lastName: 'Torres' }, address: 'Avenida 16 de Septiembre 404', city: 'León', state: 'Guanajuato' },
  { id: 8, name: { firstName: 'Guadalupe', lastName: 'Flores' }, address: 'Calle Juárez 505', city: 'Chihuahua', state: 'Chihuahua' },
  { id: 9, name: { firstName: 'Miguel', lastName: 'Morales' }, address: 'Calle Zaragoza 606', city: 'Veracruz', state: 'Veracruz' },
  { id: 10, name: { firstName: 'Fernanda', lastName: 'Gómez' }, address: 'Avenida Reforma 707', city: 'Toluca', state: 'Estado de México' },
  { id: 11, name: { firstName: 'José', lastName: 'Ruiz' }, address: 'Calle Independencia 808', city: 'Saltillo', state: 'Coahuila' },
  { id: 12, name: { firstName: 'Laura', lastName: 'Mendoza' }, address: 'Boulevard Benito Juárez 909', city: 'Aguascalientes', state: 'Aguascalientes' },
  { id: 13, name: { firstName: 'Alberto', lastName: 'Castro' }, address: 'Avenida Insurgentes 1010', city: 'Querétaro', state: 'Querétaro' },
  { id: 14, name: { firstName: 'Verónica', lastName: 'Vargas' }, address: 'Calle Pino Suárez 1111', city: 'Morelia', state: 'Michoacán' },
  { id: 15, name: { firstName: 'Hugo', lastName: 'Rojas' }, address: 'Calle Allende 1212', city: 'Oaxaca', state: 'Oaxaca' },
  { id: 16, name: { firstName: 'Elena', lastName: 'Navarro' }, address: 'Avenida Constitución 1313', city: 'San Luis Potosí', state: 'San Luis Potosí' },
  { id: 17, name: { firstName: 'Ricardo', lastName: 'Santos' }, address: 'Boulevard Belisario Domínguez 1414', city: 'Tuxtla Gutiérrez', state: 'Chiapas' },
  { id: 18, name: { firstName: 'Isabel', lastName: 'Hidalgo' }, address: 'Calle Venustiano Carranza 1515', city: 'Cancún', state: 'Quintana Roo' },
  { id: 19, name: { firstName: 'Jorge', lastName: 'Cruz' }, address: 'Calle Victoria 1616', city: 'Culiacán', state: 'Sinaloa' },
  { id: 20, name: { firstName: 'Patricia', lastName: 'Gutiérrez' }, address: 'Avenida 5 de Mayo 1717', city: 'Hermosillo', state: 'Sonora' },
  { id: 21, name: { firstName: 'Diego', lastName: 'Delgado' }, address: 'Calle Obregón 1818', city: 'Villahermosa', state: 'Tabasco' },
  { id: 22, name: { firstName: 'Rosa', lastName: 'Salazar' }, address: 'Avenida Guerrero 1919', city: 'Mexicali', state: 'Baja California' },
  { id: 23, name: { firstName: 'Manuel', lastName: 'Luna' }, address: 'Calle Morelia 2020', city: 'Acapulco', state: 'Guerrero' },
  { id: 24, name: { firstName: 'Claudia', lastName: 'Reyes' }, address: 'Calle Juárez 2121', city: 'Campeche', state: 'Campeche' },
  { id: 25, name: { firstName: 'Oscar', lastName: 'Medina' }, address: 'Avenida Hidalgo 2222', city: 'Colima', state: 'Colima' },
  { id: 26, name: { firstName: 'Paola', lastName: 'Silva' }, address: 'Calle Matamoros 2323', city: 'Tlaxcala', state: 'Tlaxcala' },
  { id: 27, name: { firstName: 'Emilio', lastName: 'Álvarez' }, address: 'Boulevard Morelos 2424', city: 'Zacatecas', state: 'Zacatecas' },
  { id: 28, name: { firstName: 'Diana', lastName: 'Ortiz' }, address: 'Calle Independencia 2525', city: 'La Paz', state: 'Baja California Sur' },
  { id: 29, name: { firstName: 'Adrián', lastName: 'Fuentes' }, address: 'Avenida Revolución 2626', city: 'Durango', state: 'Durango' },
  { id: 30, name: { firstName: 'Lucía', lastName: 'Núñez' }, address: 'Calle Zaragoza 2727', city: 'Xalapa', state: 'Veracruz' },
  { id: 31, name: { firstName: 'Raúl', lastName: 'Estrada' }, address: 'Avenida 20 de Noviembre 2828', city: 'Pachuca', state: 'Hidalgo' },
];
