// src/components/usuarios/makeData.js
export const data = [
    { name: { firstName: 'John', lastName: 'Doe' }, address: '123 Main St', city: 'Somewhere', state: 'CA' },
    { name: { firstName: 'Jane', lastName: 'Smith' }, address: '456 Elm St', city: 'Anywhere', state: 'NY' },
    { name: { firstName: 'Alice', lastName: 'Johnson' }, address: '789 Oak St', city: 'Everytown', state: 'TX' },
    { name: { firstName: 'Bob', lastName: 'Brown' }, address: '101 Pine St', city: 'Someplace', state: 'FL' },
    { name: { firstName: 'Charlie', lastName: 'Davis' }, address: '202 Maple St', city: 'Anytown', state: 'WA' },
    { name: { firstName: 'David', lastName: 'Garcia' }, address: '303 Birch St', city: 'Somewhere', state: 'OR' },
    { name: { firstName: 'Ella', lastName: 'Wilson' }, address: '404 Cedar St', city: 'Anywhere', state: 'CO' },
    { name: { firstName: 'Frank', lastName: 'Martinez' }, address: '505 Spruce St', city: 'Everytown', state: 'AZ' },
    { name: { firstName: 'Grace', lastName: 'Lopez' }, address: '606 Fir St', city: 'Someplace', state: 'NV' },
    { name: { firstName: 'Henry', lastName: 'Gonzalez' }, address: '707 Ash St', city: 'Anytown', state: 'NM' },
    { name: { firstName: 'Ivy', lastName: 'Rodriguez' }, address: '808 Willow St', city: 'Somewhere', state: 'UT' },
    { name: { firstName: 'Jack', lastName: 'Lee' }, address: '909 Poplar St', city: 'Anywhere', state: 'NV' },
    { name: { firstName: 'Kate', lastName: 'Walker' }, address: '1010 Sycamore St', city: 'Everytown', state: 'CO' },
    { name: { firstName: 'Leo', lastName: 'Hall' }, address: '1111 Redwood St', city: 'Someplace', state: 'TX' },
    { name: { firstName: 'Mia', lastName: 'Allen' }, address: '1212 Sequoia St', city: 'Anytown', state: 'CA' },
    { name: { firstName: 'Noah', lastName: 'Young' }, address: '1313 Palm St', city: 'Somewhere', state: 'FL' },
    { name: { firstName: 'Olivia', lastName: 'King' }, address: '1414 Magnolia St', city: 'Anywhere', state: 'NY' },
    { name: { firstName: 'Paul', lastName: 'Scott' }, address: '1515 Dogwood St', city: 'Everytown', state: 'WA' },
    { name: { firstName: 'Quinn', lastName: 'Green' }, address: '1616 Cypress St', city: 'Someplace', state: 'OR' },
    { name: { firstName: 'Rachel', lastName: 'Baker' }, address: '1717 Redwood St', city: 'Anytown', state: 'UT' },
    { name: { firstName: 'Sam', lastName: 'Adams' }, address: '1818 Palm St', city: 'Somewhere', state: 'AZ' },
    { name: { firstName: 'Tina', lastName: 'Nelson' }, address: '1919 Magnolia St', city: 'Anywhere', state: 'NM' },
    { name: { firstName: 'Ursula', lastName: 'Carter' }, address: '2020 Dogwood St', city: 'Everytown', state: 'CO' },
    { name: { firstName: 'Victor', lastName: 'Mitchell' }, address: '2121 Cypress St', city: 'Someplace', state: 'TX' },
    { name: { firstName: 'Wendy', lastName: 'Perez' }, address: '2222 Redwood St', city: 'Anytown', state: 'CA' },
    { name: { firstName: 'Xavier', lastName: 'Campbell' }, address: '2323 Palm St', city: 'Somewhere', state: 'FL' },
    { name: { firstName: 'Yara', lastName: 'Henderson' }, address: '2424 Magnolia St', city: 'Anywhere', state: 'NY' },
    { name: { firstName: 'Zane', lastName: 'Murphy' }, address: '2525 Dogwood St', city: 'Everytown', state: 'WA' },
    { name: { firstName: 'Amy', lastName: 'Bryant' }, address: '2626 Cypress St', city: 'Someplace', state: 'OR' },
    { name: { firstName: 'Brian', lastName: 'Sanchez' }, address: '2727 Redwood St', city: 'Anytown', state: 'UT' },
    { name: { firstName: 'Cathy', lastName: 'Reed' }, address: '2828 Palm St', city: 'Somewhere', state: 'AZ' },
  ];
  